# Change these first
owner: luratic-devs # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Datola
    url: https://datola.es
  - name: GA4 Cheatsheet
    url: https://data.ga4spy.com
  - name: GA4 SPY
    url: https://ga4spy.com
  - name: Luratic
    url: https://luratic.com
  - name: GTM SS 
    url: https://analytics.luratic.com/gtm.js?id=GTM-5D7RV9H
  - name: N8N Luratic
    url: https://n8n.luratic.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: gh.luratic.com
  baseUrl: /
  logoUrl: https://www.luratic.com/images/author/luratic.png
  name: Status
  introTitle: "**Luratic Status**"
  introMessage: "Páxina que ofrece o estado dos servizos que temos levantados en Luratic e emprega **real-time** data do noso [Repositorio de GitHub](https://github.com/upptime/upptime). Emprega a maravillosa tecnoloxía de [**Uptime**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  status-website:
    theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
